### PR TITLE
Updated the codes to match new conventions

### PR DESCRIPTION
**Pull request by the-cybersapien**
Didn't find much to change actually, just added necessary whitespace. 
Tell me if you want some changes.

### CODE REVIEW

**Review by VamsiSangam — APPROVED** [review]

**Comment by VamsiSangam** [comment]
Everything's perfect. I overlooked a minor error in your previous PR. In [QuickSortDijsktra.java](https://github.com/VamsiSangam/theoryofprogramming/blob/master/Sorting%20Algorithms/Quick%20Sort%20Algorithm/Java/QuickSortDijsktra.java#L5) line 5, please change ```Dijksrta's``` to ```Dijkstra's```.

**Comment by the-cybersapien** [comment]
Ah, okay, small typo. I've fixed it.

**Comment by the-cybersapien** [comment]
Please approve and merge this. I've got the QuickSort Dual Pivot Implementation ready for a new PR :smile:

**Comment by VamsiSangam** [comment]
Sure! Merging the PR now. 😄

**Pull request merged**
